### ISSUE TITLE
After update minion and run update-fix, minion won't launch

### ISSUE THREAD

**Issue by vlad196** [dzierzanowski/minion-linux#1]
Need copy lib folder too

`
if [[ ! -d ${script_dir}/null ]]; then
    echo "Minion doesn't appear to be in process of an update."
    exit 0
fi

cd ${script_dir}

echo "Finishing update..."

mv null/Minion-jfx.jar .
**mv null/lib/* ./lib/**
rm -r null

echo "Done!"
`

**Comment by dzierzanowski** [comment]
Thanks for the suggestion @vlad196. Could you issue a PR with the proposed fix?

**Comment by vlad196** [comment]
Added this request
